name: "Baiq Autofix"
description: "Automatic bug fixes, powered by Baiq, the IA of BQ"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  github-token:
    description: "GitHub token (use secrets.GITHUB_TOKEN)"
    required: true
  openai-api-key:
    description: "OpenAI API key"
    required: true
  model:
    description: "Model to use with Codex CLI (e.g., gpt-5.1-codex-max, o3, o4-mini)"
    required: false
    default: "gpt-5.1-codex-max"
  required-label:
    description: "Only run if the issue has this label"
    required: false
    default: "autofix"
  base-branch:
    description: "Base branch for PR (defaults to repo default branch)"
    required: false
    default: ""
  test-command-specific:
    description: "Fallback command for specific bug test (overridden by issue field 'Test command (specific test for this bug)')"
    required: false
    default: ""
  test-command-suite:
    description: "Fallback command for full test suite (overridden by issue field 'Test command (full suite for regression)')"
    required: false
    default: ""
  codex-version:
    description: "Version of @openai/codex to install (leave empty for latest)"
    required: false
    default: ""

outputs:
  pr-url:
    description: "URL of the created pull request"

runs:
  using: "node24"
  main: "dist/index.js"