name: "Baiq Autofix"
description: "Automatic bug fixes, powered by Baiq, the IA of BQ"
branding:
  icon: "git-pull-request"
  color: "purple"
inputs:
  github-token:
    description: "GitHub token (use secrets.GITHUB_TOKEN)"
    required: true
  openai-api-key:
    description: "OpenAI API key (required if using OpenAI models)"
    required: false
    default: ""
  anthropic-api-key:
    description: "Anthropic API key (required if using Claude models)"
    required: false
    default: ""
  model:
    description: "Model to use with Aider (e.g., gpt-4o, claude-3-5-sonnet-20241022, o1-preview)"
    required: false
    default: "gpt-4o"
  required-label:
    description: "Only run if the issue has this label"
    required: false
    default: "autofix"
  base-branch:
    description: "Base branch for PR (defaults to repo default branch)"
    required: false
    default: ""
  test-command-specific:
    description: "Fallback command for specific bug test (overridden by issue field 'Test command (specific test for this bug)')"
    required: false
    default: ""
  test-command-suite:
    description: "Fallback command for full test suite (overridden by issue field 'Test command (full suite for regression)')"
    required: false
    default: ""
  aider-version:
    description: "Version of aider-chat to install (leave empty for latest)"
    required: false
    default: ""
  working-directory:
    description: "Working directory for running test commands and Aider (defaults to repo root)"
    required: false
    default: ""

outputs:
  pr-url:
    description: "URL of the created pull request"

runs:
  using: "node24"
  main: "dist/index.js"
