name: Bug report (autofix-ready)
description: Bug report including user story + test case + bug description
labels:
  - bug
body:
  - type: input
    id: user_story
    attributes:
      label: User story issue (reference)
      description: Reference to the user story issue (use #123 format or full URL)
      placeholder: "#123"
    validations:
      required: true

  - type: input
    id: test_case
    attributes:
      label: Test case issue (reference)
      description: Reference to the test case that failed (use #123 format or full URL)
      placeholder: "#456"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug description
      description: Explain the bug - what is the actual result vs expected result from the test case?
      placeholder: |
        Expected: <what should happen according to the test case>
        Actual: <what actually happens - the bug>

        Additional context: <any extra information that helps understand the bug>
    validations:
      required: true

  - type: textarea
    id: automated_test
    attributes:
      label: Automated test that fails (if exists)
      description: Include command, test path/name, and failure output
      placeholder: |
        Command:
        npm run e2e:verification -- --grep "TC-1"

        Test file/name:
        e2e/verification.spec.ts - "TC-1: ..."

        Failure output:
        <paste output>
    validations:
      required: false

  - type: checkboxes
    id: autofix_gate
    attributes:
      label: Autofix gate
      description: Add the `autofix` label after filling this out to trigger the action
      options:
        - label: I confirm this issue contains enough context for an automated fix
          required: false
